version: '3.4'

services:
  samba:
    container_name: samba
    image: dperson/samba:latest
    environment:
      TZ: 'Asia/Jakarta'
    networks:
      - samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/NAS/Public:/StorageNAS-Public:z
      - /mnt/NAS/Private:/StorageNAS-Private:z
    command: '-s "PublicStorage;/StorageNAS-Public;yes;no;yes;all;username;username" -s "PrivateStorage;/StorageNAS-Private;yes;no;no;username;username" -u "username;password" -n'

networks:
  samba: