version: "3"
networks:
  proxy-network:
    # add this if the network is already existing!
    external: true
  nextcloud-network:

services:
  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - /opt/docker/nextcloud/nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextCloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    networks:
      - proxy-network
      - nextcloud-network

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /opt/docker/nextcloud/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootNextCloud
      - MYSQL_PASSWORD=nextCloud445
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud-network
